default_install_hook_types: [pre-commit, commit-msg]
exclude: (?x)^(
              main.py|
          )$

repos:
  - hooks:
      - id: autoflake

    repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1

  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.12.0

  - hooks:
      - id: black
        language_version: python3.11
        stages:
          - commit
    repo: https://github.com/psf/black
    rev: 23.1.0

  - hooks:
      - id: pylint
        name: pylint
        language: system
        types: [ python ]
        pass_filenames: true
        entry: pylint
        stages:
          - commit
        args:
          - --rcfile=pyproject.toml
    repo: local

  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0


